application: devn-uplusprofiles
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js
- url: /stylesheets
  static_dir: stylesheets
- url: /img
  static_dir: img
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest

builtins:
- remote_api: on
