application: devn-uplusprofiles
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon.png
  static_files: /img/favicon.png
  upload: /img/favicon.png

- url: /js
  static_dir: js

- url: /stylesheets
  static_dir: stylesheets

- url: /img
  static_dir: img

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- remote_api: on