__ALL__ = ['sources',
           'courses',
           'username1',
           'username2',
           'password1',
           'password2',
           'email1',
           'email2',
           'pv',
           'uv',
           'title_plain_text',
           'content_plain_text',
           'title_plain_text2',
           'content_plain_text2']
