application: uplusmessagingdemo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest